# Analysis {#analysis}

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Import Packages
```{r, message=FALSE}
library(moments)
library(dplyr)
library(tidyr)
library(stats)
library(sjstats)
library(ggplot2)
```

```{r}

fin <- read.csv('Proj1Data/cleanFinancials1519.csv')
dem <- read.csv('Proj1Data/cleanDemographics1519.csv')

fin$r_status <- factor(fin$r_status, levels = c("R1", "R2"), labels = c(1,2))
dem$r_status <- factor(dem$r_status, levels = c("R1", "R2"), labels = c(1,2))

```

 Hello world
## Transform Datasets
```{r}

finR <- fin[fin$year == "latest",]
finR1 <- fin[fin$r_status == 1 & fin$year == "latest",]
finR2 <- fin[fin$r_status == 2 & fin$year == "latest",]
demR <- dem[dem$year == "latest",]
demR1 <- dem[dem$r_status == 1 & dem$year == "latest",]
demR2 <- dem[dem$r_status == 2 & dem$year == "latest",]

finR <- subset(finR, university %in% demR$university)

```

## Descriptives

```{r}
# Demographics
summary(demR1$white)
skewness(demR1$white)
kurtosis(demR1$white)

summary(demR2$white)
skewness(demR2$white)
kurtosis(demR2$white)

# Cost
print('Tuition cost')

summary(finR1$costt4_a)
cost_hist1 <- ggplot(finR1, aes(x =costt4_a)) + 
  geom_histogram(bins = 40, color = "black", fill = "red") +
  labs(title = "Distribution of Tuition Costs at R1s", 
       subtitle = "", 
       x = "Cost (in American dollars)", 
       y = "Frequency") 
cost_hist1


summary(finR2$costt4_a)
cost_hist2 <- ggplot(finR2, aes(x =costt4_a)) + 
  geom_histogram(bins = 40, color = "black", fill = "pink") +
  labs(title = "Distribution of Tuition Costs at R2s", 
       subtitle = "", 
       x = "Cost (in American dollars)", 
       y = "Frequency") 
cost_hist2

# Students debt
print('Student debt')
summary(finR1$grad_debt_mdn)
debt_hist1 <- ggplot(finR1, aes(x = grad_debt_mdn)) + 
  geom_histogram(bins = 40, color = "black", fill = "cadetblue4") +
  labs(title = "Distribution of Median Student Debt at R1s", 
       subtitle = "", 
       x = "Median Debt (in American dollars)", 
       y = "Frequency") 
debt_hist1

summary(finR2$grad_debt_mdn)
debt_hist1 <- ggplot(finR2, aes(x = grad_debt_mdn)) + 
  geom_histogram(bins = 40, color = "black", fill = "cadetblue3") +
  labs(title = "Distribution of Median Student Debt at R2s", 
       subtitle = "", 
       x = "Median Debt (in American dollars)", 
       y = "Frequency") 
debt_hist1

# Unemployment
print('Unemployment Rate')
summary(finR1$unemp_rate)
unemp_hist1 <- ggplot(finR1, aes(x = unemp_rate)) + 
  geom_histogram(bins = 40, color = "black", fill = "darkseagreen4") +
  labs(title = "Distribution of Post-Graduation Unemployment rates at R1s", 
       subtitle = "", 
       x = "Unemployment Rate", 
       y = "Frequency") 
unemp_hist1

summary(finR2$unemp_rate)
unemp_hist2 <- ggplot(finR2, aes(x = unemp_rate)) + 
  geom_histogram(bins = 40, color = "black", fill = "darkseagreen3") +
  labs(title = "Distribution of Post-Graduation Unemployment rates at R2s", 
       subtitle = "", 
       x = "Unemployment Rate", 
       y = "Frequency") 
unemp_hist2
```

## Wilcox for skewed bois
```{r}
# R1 associated with student outcomes
# debt, skewed to all hell so non parametric t-test.  
wilcox.test(formula=finR$grad_debt_mdn~finR$r_status)
# debt for R2 unis significantly differed from R1 students.

# non-working
t.test(finR$unemp_rate~finR$r_status)
```

```{r}
# cost differences between R1, R2.

# t.test(finR$costt4_a~finR$r_status)

# Cant do a t-test cause of the bimodal abomination

# Average annual R1 tuition cost: 41,571.97
# Average annual R2 tuition cost: 33,958.16
```

```{r}
# white people proportion and unemployment

cor(demR$white, finR$unemp_rate, use = 'complete.obs')

# results: White proportion is negatively associated with unemployment (r = -0.49)
```

## Main model
```{r}
ggplot(finR, aes(unemp_rate, demR$white,colour=r_status)) + geom_point() + geom_smooth(method = "lm")
```

## Main model
```{r}
# 3 White proportion moderates unemployment outcomes. 
predictor <- as.integer(finR$r_status)
moderator <- demR$white
interaction <- predictor * moderator
outcome <- finR$unemp_rate

wlm <- lm(formula = outcome ~ predictor + moderator + interaction)
summary(wlm)
```

### Decomposition

#### Simple model
```{r}
predictor <- finR$r_status
outcome <- finR$unemp_rate
simplelm <- lm(formula = outcome ~ predictor)
summary(simplelm)
```

#### Moderator direct effect
```{r}
predictor <- demR$white
outcome <- finR$unemp_rate
moderatorlm <- lm(formula = outcome ~ predictor)
summary(moderatorlm)
```

#### Interaction Effect
```{r}
predictor <- as.integer(finR$r_status)
moderator <- demR$white
interaction <- predictor * moderator
outcome <- finR$unemp_rate

interactionlm <- lm(formula = outcome ~ interaction)
summary(moderatorlm)
```
