# Data Clean {#clean}

```{r}
library(tidyverse)
```

Accessibility
: The data was easily retrievable, the only difficulty was using the API key to retrieve everything into R so we could clean, manipulate, and analyze the data.

Appropriate Amount of Data
: The data had mostly what we were looking for. However, it would have been nice if the data included records of type of school (State vs Liberal Arts vs Ivy League) or average class sizes. This would allow us to look for other correlations or lurking variables between the financial data. Overall, the data was appropriate for our analysis.

Believability
: There is no reason for us to assume the data would be intentionally falsified as it was collected by the U.S. Government to simply compare costs and values of higher education institutions. There have been claims from some colleges (such as Boston University) that there are inaccuracies in the data, however.

Concise Representation
: The data is difficult to navigate through without frequent cross-checking of the documentation. There are many columns that look quite similar but are entirely different measures and statistics.

Consistent Representation
:The data is presented in the same format consistently throughout the dataset.

Ease of Manipulation 
: The data had to be cleaned before any manipulation took place but once that was completed, the data was easy to manipulate.

Free-of-Error 
: The data is correct and reliable except for the N/A values that were present before cleaning.

Interpretability 
: The data is difficult to interpret without referencing to the documentation continuously. Without the documentation, this dataset would have been very difficult to interpret as a stand-alone.

Objectivity 
: The data could be biased as we are looking at institutions which are typically attended to by upper class people. Depending on how the data is interpreted, it could lead to incorrect inferences as there could be many lurking variables unaccounted for.

Relevancy 
: The data is well tailored to what we were looking for. Many of the questions we asked were answerable by the data.

Reputation 
: The data is well regarded as it has been used for other studies and was introduced by Obama in 2015. It highlighted the Pell grant problem and other financial issues being faced by college students across the country. 

Security 
: The data is highly secured as it was contained and dispersed by the United States Government. We have no doubts that the security of the data was ever compromised.

Timeliness 
: The data is mostly up to date, but it would have been nice to have more recent statistics being recorded as financial data can change quickly as a product of circumstances; like a pandemic.

Understandability
: The data set in-and-of itself was rather complicated, and the documentation did little to assist in approaching the analysis in R. That being said, the data may be more suited for analysts familiar with JSON


```{r}
dem <- read.csv("Proj1Data/Demographics15to19.csv")

dem_clean <- dem[,-c(1, 17, 20:24)] %>%
  rename("university" = instnm,
  "r_status" = ccbasic, 
  "state" = stabbr, 
  "white" = ugds_white, 
  "black" = ugds_black, 
  "hispanic" = ugds_hisp, 
  "asian" = ugds_asian, 
  "indigenous" = ugds_aian, 
  "nhpi" = ugds_nhpi, 
  "nra" = ugds_nra, 
  "unknown" = ugds_unkn) %>% 
  drop_na(black)

dem_clean$r_status <- recode(dem_clean$r_status, `15` = 'R1', `16` = "R2")

dem_clean <- dem_clean %>%  
  group_by(r_status) %>%
  mutate_at(c("female", "first_gen", "poverty_rate", "veteran", "unemp_rate"), funs(ifelse(is.na(.), mean(., na.rm = TRUE),.)))


write.csv(dem_clean, "Proj1Data/cleanDemographics1519.csv")
```

```{r}
fin <- read.csv('Proj1Data/Financials15to19.csv')

fin_clean <- fin[,-c(2)] %>%
  rename("university" = instnm,
  "r_status" = ccbasic, 
  "state" = stabbr)

fin_clean$r_status <- recode(fin_clean$r_status, `15` = 'R1', `16` = "R2")

```

```{r}
head(fin_clean) %>% MakePretty()
```

```{r}
write.csv(fin_clean, "Proj1Data/cleanFinancials1519.csv")
```
