# Discussion {#discussion}

## Discussion

  These results are meant to serve as illustration of the data in the College Scorecard API pertaining to schools at the highest levels of Carnegie Classification. In addition to the descriptive analysis, which demonstrates the distributions of demographics and financial data, our regression analysis demonstrates that the distinction between R1 or R2 classifications has a significant, albeit small effect on unemployment rates for graduates from these universities. Interestingly, the relationship between unemployment and School type was moderated by the proportion of white people at a given university. Commentary on the social conditions surrounding this relationship is beyond the scope of this project and the researchers’ expertise; nevertheless, we hope these results serve others in discussions of systemic issues related to race and higher education.

## The Project Process
    
  We should admit that at the onset of this project our team was lost in the complexity of the data in the College Scorecard API. This was largely due to our own stubbornness, as we wanted to use the API because of the advantages this method offers in regards to reproducibility. That being said, our project scope began to grow exponentially after learning about the rscorecard package, which not only offered a highly interpretable method for extracting the data but also offered further insight into how the data from the API was structured in and of itself.     
Prior to developing a plan for our analysis (or even a direction for the project) we began by setting up the repositories and collaborative documents that we planned to use throughout the project. The primary collaborative tools were GitHub, Google Docs, and Discord. We used Discord to keep in contact because of their native support for markdown as part of their messaging service, which allowed us to send code chunks directly to each other, as well as the voice-conferencing and screen sharing functionality that allowed us to meet and discuss progress. The Google Docs were primarily used for planning and drafting the written portions of our project. Lastly, we used github to share files with one another and used the gitpages feature to host the final document as a web page. 

The documents in the [CollegeScorecardProjectBook](https://github.com/KalaniStanton/CollegeScorecardProjectBook) repository contain all of the code, data, and configuration files needed in order to knit the bookdown on each team member’s computer. Ultimately, this means that a cloned repository of our GitHub should run and knit, just as long as the user acquires their own API key and installs all the necessary dependencies into their RStudio environment.
In truth, this project suffered from quite a bit of “feature creep” once we began working on the project in earnest. As we finally began to understand the data, we realized there were a lot of ways that we could take full advantage of the information at our disposal using the specialized skill sets of our team members. Consequently, we were unable to discuss all of the visualizations that we had made during this process, but have included them in case anyone would like to use our code as reference for their own exploratory projects in the future.

## Things Learned & Skills Acquired

### Adam
I was incredibly surprised by how much we were able to glean from only a handful of variables of interest. We definitely came into the exploratory analysis ‘laptops blazing’ to burn down the ivory R1 throne but alas the dataset managed to both defuse our animosity and reveal a much more realistic painting of R1 characteristics. I feel that we were able to learn alot about the diversity characteristics and outcomes of R1 vs R2 schools in spite of the project’s fairly narrow scope. On a different note, I really enjoyed getting to work with holistically skewed and messy data. On a longer time scale I would have loved to seek out and model some of the more obscure latent variables and their relation to student outcomes. 

>“people use statistics the same way that a drunk uses a lamppost. 
>   More for support than for illumination.”
                      Andrew Lang, a long ass time ago

### Kalani
  
Despite my previous endeavors with Bookdown (I had knit one years ago), I struggled to navigate the highly technical documentation available for this package. Nevertheless, I persisted and was able to create a clean document format that parallelled the fantastic work put in by my other team members. Through Adam’s work on statistical analysis, I became re-acquainted with some of the modeling and statistical tools I had used in my undergrad data science and psychology classes, but had also learned more about experimental design from Adam himself. I also collaborated with Sara to make the interactive chloropleth maps using plotly, which I had never done before and am happy I took the time to learn. All in all, I’m really pleased with this project and appreciated the diverse skill set across the members of this team. 

> "There is no such thing as a 'good' programmer; 
>   just a competent googler."
                         ~Unknown

### Sara 
Most of what I learned from this project I learned from my partners. Kalani's Bookdown and data-wrangling ingenuity and Adam's statistics proficiency added layers to the learning experience, and made the assignment fun to work on. I also enjoyed reading Ben’s interpretation of the subjective data quality features.  I was impressed by how much we were able to do with a fairly sparse and limited data set. We managed to probe at a topic I find genuinely interesting, and scrape insights from below the surface level of the data. I also enjoyed being able to implement the data quality functions I created for the homework assignment on actual data sets. It provided meaning to the work we had completed so far. 

### Ben

This group project gave us all some much-needed group work experience as well as sharpened our technical skills in R and Git. We collaborated using a Git Repository and Kalani used Bookdown for the formal writeup. It was an interesting experience, and we all were able to contribute in our own way. As for what we learned, the dataset showed us real data about the distribution and diversity of colleges across the United States. When we usually think about these institutions, we come in with our own pre -conceived biases and opinions but when we look at the actual data, we can begin to formulate real inferences and conclusions. In our other works, we haven’t had this experience yet, so it was a nice change of pace.

## Other fun things 

Features that we were interested in, but didn't get a chance to follow through on or did not align with the primary goal of the project. :)

### Gender 

```{r}

#Universities with the highest female/male ratio, the top 10 are mostly R2's for both categories

cdem %>%
  arrange(desc(female)) %>%
  filter(female > .50) %>%
  distinct(university, .keep_all = TRUE) %>%
  head(10)

cdem %>%
  arrange(female) %>%
  filter(female < .50) %>%
  distinct(university, .keep_all = TRUE) %>%
  head(10)

R1s <- cdem %>%
  filter(r_status == 1)

ggplot(cdem, aes(x = female)) + 
  geom_histogram(bins = 40, color = "black", fill = "pink") + 
  labs(title = "Distribution of Female/Male Gender ratio at R1s")

R2s <- cdem %>%
  filter(r_status == 2)

ggplot(R2s, aes(x = female)) + 
  geom_histogram(bins = 40, color = "black", fill = "skyblue") + 
  labs(title = "Distribution of Female/Male Gender ratio at R2s")

```
