--- 
title: "A Minimal Book Example"
author: "Sara Haman, Adam Lashley, Reilly Stanton, Benjamin Weisman"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
output_dir: "docs"
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes~
github-repo:  KalaniStanton/CollegeScorecardProjectBook 
description: "An analysis of data from the College Scorecard API, which focuses on differences identified between institutions with R1 and R2 carnegie classifications."
---

# Preface {-}

This project was completed to satisfy the requirements of a project assigned to students in the Fall 2020 Data Munging and Exploratory Data Analysis at New College of Florida.

This project is broken down into sections pertaining to the different steps in exploratory data analysis. In our \@ref(intro) we give an overview of this project, followed by an explanation of our process for selecting variables. Next, in the \@ref(import) section we demonstrate our initial ~~failed~~ attempts at pulling the data directly from the API, and explain why we chose to pivot to using the `{rscorecard}` package for querying our data from the API. Once the data is imported, we assess the quality of the data in the \@ref(clean) section of our analysis and rename some of the variables to make the data set, and our later analysis, easier to interpret. Following this, the \@ref(analysis) section contains the statistical analysis of the data, wherein we investigate the relationship between R1 and R2 carnegie classification status and unemployment rates. This model is the modified by adding the proportion of white studens as a moderator, which reveals interesting results. Lastly, in the \@ref(discussion) section, we present visualizations made using the data from the College Scorecard API and elaborate on the statistical analyses performed in the previous section.

```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```
