<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Section 5 Methods and Results | An Exploratory Analysis of Data in the U.S. College Scorecard</title>
  <meta name="description" content="An analysis of data from the College Scorecard API, which focuses on differences identified between institutions with R1 and R2 carnegie classifications." />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="Section 5 Methods and Results | An Exploratory Analysis of Data in the U.S. College Scorecard" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="An analysis of data from the College Scorecard API, which focuses on differences identified between institutions with R1 and R2 carnegie classifications." />
  <meta name="github-repo" content="KalaniStanton/CollegeScorecardProjectBook" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Section 5 Methods and Results | An Exploratory Analysis of Data in the U.S. College Scorecard" />
  
  <meta name="twitter:description" content="An analysis of data from the College Scorecard API, which focuses on differences identified between institutions with R1 and R2 carnegie classifications." />
  

<meta name="author" content="Sara Haman, Adam Lashley, Reilly Stanton, Benjamin Weisman" />


<meta name="date" content="2020-10-19" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="clean.html"/>
<link rel="next" href="discussion.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<link href="libs/bsTable-3.3.7/bootstrapTable.min.css" rel="stylesheet" />
<script src="libs/bsTable-3.3.7/bootstrapTable.js"></script>
<script src="libs/htmlwidgets-1.5.1/htmlwidgets.js"></script>
<script src="libs/plotly-binding-4.9.2.1/plotly.js"></script>
<script src="libs/typedarray-0.1/typedarray.min.js"></script>
<link href="libs/crosstalk-1.1.0.1/css/crosstalk.css" rel="stylesheet" />
<script src="libs/crosstalk-1.1.0.1/js/crosstalk.min.js"></script>
<link href="libs/plotly-htmlwidgets-css-1.52.2/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="libs/plotly-main-1.52.2/plotly-latest.min.js"></script>


<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">College Scorecard EDA</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="chapter" data-level="1" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>1</b> Introduction</a></li>
<li class="chapter" data-level="2" data-path="import.html"><a href="import.html"><i class="fa fa-check"></i><b>2</b> Data Acquisition</a><ul>
<li class="chapter" data-level="2.1" data-path="import.html"><a href="import.html#set-up-and-api-exploration"><i class="fa fa-check"></i><b>2.1</b> Set-up and API Exploration</a><ul>
<li class="chapter" data-level="2.1.1" data-path="import.html"><a href="import.html#project-directory-management"><i class="fa fa-check"></i><b>2.1.1</b> Project Directory Management</a></li>
<li class="chapter" data-level="2.1.2" data-path="import.html"><a href="import.html#api-exploration"><i class="fa fa-check"></i><b>2.1.2</b> API Exploration</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="import.html"><a href="import.html#the-rscorecard-and-tidyverse-approach"><i class="fa fa-check"></i><b>2.2</b> The <code>rscorecard</code> and <code>tidyverse</code> approach</a><ul>
<li class="chapter" data-level="2.2.1" data-path="import.html"><a href="import.html#finances"><i class="fa fa-check"></i><b>2.2.1</b> Finances</a></li>
<li class="chapter" data-level="2.2.2" data-path="import.html"><a href="import.html#demographics"><i class="fa fa-check"></i><b>2.2.2</b> Demographics</a></li>
<li class="chapter" data-level="2.2.3" data-path="import.html"><a href="import.html#death"><i class="fa fa-check"></i><b>2.2.3</b> Death</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="quality.html"><a href="quality.html"><i class="fa fa-check"></i><b>3</b> Data Quality</a><ul>
<li class="chapter" data-level="3.1" data-path="quality.html"><a href="quality.html#set-up"><i class="fa fa-check"></i><b>3.1</b> Set-up</a></li>
<li class="chapter" data-level="3.2" data-path="quality.html"><a href="quality.html#the-functions"><i class="fa fa-check"></i><b>3.2</b> The Functions</a></li>
<li class="chapter" data-level="3.3" data-path="quality.html"><a href="quality.html#the-evaluations"><i class="fa fa-check"></i><b>3.3</b> The Evaluations</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="clean.html"><a href="clean.html"><i class="fa fa-check"></i><b>4</b> Data Cleaning</a><ul>
<li class="chapter" data-level="4.1" data-path="clean.html"><a href="clean.html#demographics-1"><i class="fa fa-check"></i><b>4.1</b> Demographics</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="analysis.html"><a href="analysis.html"><i class="fa fa-check"></i><b>5</b> Methods and Results</a><ul>
<li class="chapter" data-level="5.1" data-path="analysis.html"><a href="analysis.html#methods"><i class="fa fa-check"></i><b>5.1</b> Methods</a></li>
<li class="chapter" data-level="5.2" data-path="analysis.html"><a href="analysis.html#results"><i class="fa fa-check"></i><b>5.2</b> Results</a><ul>
<li class="chapter" data-level="5.2.1" data-path="analysis.html"><a href="analysis.html#demographic-descriptive-statistics"><i class="fa fa-check"></i><b>5.2.1</b> Demographic Descriptive Statistics</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="analysis.html"><a href="analysis.html#financial-descriptive-statistics"><i class="fa fa-check"></i><b>5.3</b> Financial Descriptive Statistics</a><ul>
<li class="chapter" data-level="5.3.1" data-path="analysis.html"><a href="analysis.html#r1s-vs.-r2s"><i class="fa fa-check"></i><b>5.3.1</b> R1s vs. R2s</a></li>
<li class="chapter" data-level="5.3.2" data-path="analysis.html"><a href="analysis.html#regression-model"><i class="fa fa-check"></i><b>5.3.2</b> Regression model</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="discussion.html"><a href="discussion.html"><i class="fa fa-check"></i><b>6</b> Discussion</a><ul>
<li class="chapter" data-level="6.1" data-path="discussion.html"><a href="discussion.html#other-fun-things---interactive-chloropleths"><i class="fa fa-check"></i><b>6.1</b> Other fun things - Interactive Chloropleths</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">An Exploratory Analysis of Data in the U.S. College Scorecard</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="analysis" class="section level1">
<h1><span class="header-section-number">Section 5</span> Methods and Results</h1>
<div id="methods" class="section level2">
<h2><span class="header-section-number">5.1</span> Methods</h2>
<dl>
<dt><strong>Sample.</strong></dt>
<dd>The sample for this study consisted of universities in the United States of America. In this way, we were able to examine what was nearly the population of college students in America. However, the high frequency of NA variables in some categories hindered
</dd>
<dt><strong>Procedure.</strong></dt>
<dd>The data was collected by accessing the public College Scorecard API. The procedure for extracting and cleaning the data is explained in the Data Extraction and Data Clean sections.
</dd>
<dt><strong>Analysis Strategy.</strong></dt>
<dd>We quantified student outcomes using the median debt and unemployment rate variables. These variables were selected because they are tangibly related to financial outcomes. Other potential measures of success in the data, such as completion rates and death rates, contained either very sparse data or were ambiguous. For instance, neither transferring nor withdrawing from a University are necessarily indicative of a poor outcome (insofar as it relates to student success after attending the University). Both debt and unemployment, however, are. High rates of debt implicate a school with insufficient financial aid programs. High debt medians also potentially imply student’s are not placed into high-paying jobs that would allow them to expediently repay their debt. High rates of unemployment suggest that students have trouble finding jobs after graduation. As the goal of a university education is largely to educate a student to assist with their career, students being unable to find jobs is a poor outcome.
</dd>
</dl>
<p>The demographic variables were selected by inspecting all the demographic variables in the dataset and selecting the ones that were mostly complete. We decided to look at the demographic makeup of R1 and R2 universities to determine if there was a significant difference between the student body profiles. Race and gender are often discussed in relation to student success, due to a history of systematic discrimination within the American university system. These were our primary variables of interest. Specifically, we were interested in the ratio of White students to minority students. However, we briefly examined veteran and first generation status.</p>
</div>
<div id="results" class="section level2">
<h2><span class="header-section-number">5.2</span> Results</h2>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb68-1"><a href="analysis.html#cb68-1"></a><span class="kw">library</span>(moments)</span>
<span id="cb68-2"><a href="analysis.html#cb68-2"></a><span class="kw">library</span>(dplyr)</span>
<span id="cb68-3"><a href="analysis.html#cb68-3"></a><span class="kw">library</span>(tidyr)</span>
<span id="cb68-4"><a href="analysis.html#cb68-4"></a><span class="kw">library</span>(stats)</span>
<span id="cb68-5"><a href="analysis.html#cb68-5"></a><span class="kw">library</span>(sjstats)</span>
<span id="cb68-6"><a href="analysis.html#cb68-6"></a><span class="kw">library</span>(ggplot2)</span>
<span id="cb68-7"><a href="analysis.html#cb68-7"></a><span class="kw">library</span>(plotly)</span>
<span id="cb68-8"><a href="analysis.html#cb68-8"></a><span class="kw">library</span>(tidyverse)</span>
<span id="cb68-9"><a href="analysis.html#cb68-9"></a><span class="kw">library</span>(purrr)</span>
<span id="cb68-10"><a href="analysis.html#cb68-10"></a><span class="kw">library</span>(RColorBrewer)</span>
<span id="cb68-11"><a href="analysis.html#cb68-11"></a><span class="kw">library</span>(tmap)</span></code></pre></div>
<div class="sourceCode" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb69-1"><a href="analysis.html#cb69-1"></a><span class="co">#READING IN THE CSVs</span></span>
<span id="cb69-2"><a href="analysis.html#cb69-2"></a></span>
<span id="cb69-3"><a href="analysis.html#cb69-3"></a>fin &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&#39;Proj1Data/cleanFinancials1519.csv&#39;</span>)</span>
<span id="cb69-4"><a href="analysis.html#cb69-4"></a>dem &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&#39;Proj1Data/cleanDemographics1519.csv&#39;</span>)</span>
<span id="cb69-5"><a href="analysis.html#cb69-5"></a>fin<span class="op">$</span>r_status &lt;-<span class="st"> </span><span class="kw">factor</span>(fin<span class="op">$</span>r_status, <span class="dt">levels =</span> <span class="kw">c</span>(<span class="st">&quot;R1&quot;</span>, <span class="st">&quot;R2&quot;</span>), <span class="dt">labels =</span> <span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))</span>
<span id="cb69-6"><a href="analysis.html#cb69-6"></a>dem<span class="op">$</span>r_status &lt;-<span class="st"> </span><span class="kw">factor</span>(dem<span class="op">$</span>r_status, <span class="dt">levels =</span> <span class="kw">c</span>(<span class="st">&quot;R1&quot;</span>, <span class="st">&quot;R2&quot;</span>), <span class="dt">labels =</span> <span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))</span>
<span id="cb69-7"><a href="analysis.html#cb69-7"></a></span>
<span id="cb69-8"><a href="analysis.html#cb69-8"></a><span class="co">#TRANSFORMING THE DATASETS </span></span>
<span id="cb69-9"><a href="analysis.html#cb69-9"></a></span>
<span id="cb69-10"><a href="analysis.html#cb69-10"></a>finR &lt;-<span class="st"> </span>fin[fin<span class="op">$</span>year <span class="op">==</span><span class="st"> &quot;latest&quot;</span>,]</span>
<span id="cb69-11"><a href="analysis.html#cb69-11"></a>finR1 &lt;-<span class="st"> </span>fin[fin<span class="op">$</span>r_status <span class="op">==</span><span class="st"> </span><span class="dv">1</span> <span class="op">&amp;</span><span class="st"> </span>fin<span class="op">$</span>year <span class="op">==</span><span class="st"> &quot;latest&quot;</span>,]</span>
<span id="cb69-12"><a href="analysis.html#cb69-12"></a>finR2 &lt;-<span class="st"> </span>fin[fin<span class="op">$</span>r_status <span class="op">==</span><span class="st"> </span><span class="dv">2</span> <span class="op">&amp;</span><span class="st"> </span>fin<span class="op">$</span>year <span class="op">==</span><span class="st"> &quot;latest&quot;</span>,]</span>
<span id="cb69-13"><a href="analysis.html#cb69-13"></a>demR &lt;-<span class="st"> </span>dem[dem<span class="op">$</span>year <span class="op">==</span><span class="st"> &quot;latest&quot;</span>,]</span>
<span id="cb69-14"><a href="analysis.html#cb69-14"></a>demR1 &lt;-<span class="st"> </span>dem[dem<span class="op">$</span>r_status <span class="op">==</span><span class="st"> </span><span class="dv">1</span> <span class="op">&amp;</span><span class="st"> </span>dem<span class="op">$</span>year <span class="op">==</span><span class="st"> &quot;latest&quot;</span>,]</span>
<span id="cb69-15"><a href="analysis.html#cb69-15"></a>demR2 &lt;-<span class="st"> </span>dem[dem<span class="op">$</span>r_status <span class="op">==</span><span class="st"> </span><span class="dv">2</span> <span class="op">&amp;</span><span class="st"> </span>dem<span class="op">$</span>year <span class="op">==</span><span class="st"> &quot;latest&quot;</span>,]</span>
<span id="cb69-16"><a href="analysis.html#cb69-16"></a>finR &lt;-<span class="st"> </span><span class="kw">subset</span>(finR, university <span class="op">%in%</span><span class="st"> </span>demR<span class="op">$</span>university)</span></code></pre></div>
<div id="demographic-descriptive-statistics" class="section level3">
<h3><span class="header-section-number">5.2.1</span> Demographic Descriptive Statistics</h3>
<p><strong>LOCATION OF R1’S vs. R2’S</strong></p>
<p>Before analyzing the demographic differences, we thought it was important to display how R1 and R2 schools are distributed across the United States. The demographic makeup of a school is potentially influenced by the demographics of in-state students which, at least at public institutions, are proportionally more likely to attend the school than students from any other state (see State Council of Higher Education for Virginia, 2019 for a case study of one state). Although we do not factor state and baseline state demographics into our model, it is a potential influential third variable that should be kept in mind while interpretting race and income demographics.</p>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb70-1"><a href="analysis.html#cb70-1"></a>r1_state &lt;-<span class="st"> </span>cdem <span class="op">%&gt;%</span></span>
<span id="cb70-2"><a href="analysis.html#cb70-2"></a><span class="st">  </span><span class="kw">filter</span>(r_status <span class="op">==</span><span class="st"> &quot;R1&quot;</span>) <span class="op">%&gt;%</span></span>
<span id="cb70-3"><a href="analysis.html#cb70-3"></a><span class="st">  </span><span class="kw">group_by</span>(state) <span class="op">%&gt;%</span></span>
<span id="cb70-4"><a href="analysis.html#cb70-4"></a><span class="st">  </span><span class="kw">distinct</span>(university) <span class="op">%&gt;%</span></span>
<span id="cb70-5"><a href="analysis.html#cb70-5"></a><span class="st">  </span><span class="kw">count</span>()</span>
<span id="cb70-6"><a href="analysis.html#cb70-6"></a></span>
<span id="cb70-7"><a href="analysis.html#cb70-7"></a>r2_state &lt;-<span class="st"> </span>cdem <span class="op">%&gt;%</span></span>
<span id="cb70-8"><a href="analysis.html#cb70-8"></a><span class="st">  </span><span class="kw">filter</span>(r_status <span class="op">==</span><span class="st"> &quot;R2&quot;</span>) <span class="op">%&gt;%</span></span>
<span id="cb70-9"><a href="analysis.html#cb70-9"></a><span class="st">  </span><span class="kw">group_by</span>(state) <span class="op">%&gt;%</span></span>
<span id="cb70-10"><a href="analysis.html#cb70-10"></a><span class="st">  </span><span class="kw">distinct</span>(university) <span class="op">%&gt;%</span></span>
<span id="cb70-11"><a href="analysis.html#cb70-11"></a><span class="st">  </span><span class="kw">count</span>()</span></code></pre></div>
<div class="sourceCode" id="cb71"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb71-1"><a href="analysis.html#cb71-1"></a>g &lt;-<span class="st"> </span><span class="kw">list</span>(</span>
<span id="cb71-2"><a href="analysis.html#cb71-2"></a>  <span class="dt">scope =</span> <span class="st">&#39;usa&#39;</span>,</span>
<span id="cb71-3"><a href="analysis.html#cb71-3"></a>  <span class="dt">projection =</span> <span class="kw">list</span>(<span class="dt">type =</span> <span class="st">&#39;albers usa&#39;</span>),</span>
<span id="cb71-4"><a href="analysis.html#cb71-4"></a>  <span class="dt">lakecolor =</span> <span class="kw">toRGB</span>(<span class="st">&#39;white&#39;</span>)</span>
<span id="cb71-5"><a href="analysis.html#cb71-5"></a>)</span>
<span id="cb71-6"><a href="analysis.html#cb71-6"></a></span>
<span id="cb71-7"><a href="analysis.html#cb71-7"></a>r1_map &lt;-<span class="st"> </span><span class="kw">plot_geo</span>() <span class="op">%&gt;%</span></span>
<span id="cb71-8"><a href="analysis.html#cb71-8"></a><span class="st">  </span><span class="kw">add_trace</span>(</span>
<span id="cb71-9"><a href="analysis.html#cb71-9"></a>    <span class="dt">z =</span> <span class="op">~</span>r1_state<span class="op">$</span>n,</span>
<span id="cb71-10"><a href="analysis.html#cb71-10"></a>    <span class="dt">span =</span> <span class="kw">I</span>(<span class="dv">1</span>),</span>
<span id="cb71-11"><a href="analysis.html#cb71-11"></a>    <span class="dt">colorscale =</span> <span class="st">&#39;Portland&#39;</span>,</span>
<span id="cb71-12"><a href="analysis.html#cb71-12"></a>    <span class="dt">zauto =</span> F,</span>
<span id="cb71-13"><a href="analysis.html#cb71-13"></a>    <span class="dt">zmax =</span> <span class="dv">10</span>,</span>
<span id="cb71-14"><a href="analysis.html#cb71-14"></a>    <span class="dt">zmin =</span> <span class="dv">1</span>,</span>
<span id="cb71-15"><a href="analysis.html#cb71-15"></a>    <span class="dt">locations =</span> r1_state<span class="op">$</span>state, </span>
<span id="cb71-16"><a href="analysis.html#cb71-16"></a>    <span class="dt">locationmode =</span> <span class="st">&#39;USA-states&#39;</span></span>
<span id="cb71-17"><a href="analysis.html#cb71-17"></a>  ) <span class="op">%&gt;%</span></span>
<span id="cb71-18"><a href="analysis.html#cb71-18"></a><span class="st">  </span><span class="kw">colorbar</span>(<span class="dt">title =</span> <span class="st">&quot;# of Schools&quot;</span>) <span class="op">%&gt;%</span></span>
<span id="cb71-19"><a href="analysis.html#cb71-19"></a><span class="st">  </span><span class="kw">layout</span>(<span class="dt">geo =</span> g, <span class="dt">title =</span> <span class="st">&quot;Number of R1 Schools per State&quot;</span>)</span>
<span id="cb71-20"><a href="analysis.html#cb71-20"></a></span>
<span id="cb71-21"><a href="analysis.html#cb71-21"></a>r2_map &lt;-<span class="st"> </span><span class="kw">plot_geo</span>() <span class="op">%&gt;%</span></span>
<span id="cb71-22"><a href="analysis.html#cb71-22"></a><span class="st">  </span><span class="kw">add_trace</span>(</span>
<span id="cb71-23"><a href="analysis.html#cb71-23"></a>    <span class="dt">z =</span> <span class="op">~</span>r2_state<span class="op">$</span>n,</span>
<span id="cb71-24"><a href="analysis.html#cb71-24"></a>    <span class="dt">span =</span> <span class="kw">I</span>(<span class="dv">1</span>),</span>
<span id="cb71-25"><a href="analysis.html#cb71-25"></a>    <span class="dt">colorscale =</span> <span class="st">&#39;Portland&#39;</span>,</span>
<span id="cb71-26"><a href="analysis.html#cb71-26"></a>    <span class="dt">zauto =</span> F,</span>
<span id="cb71-27"><a href="analysis.html#cb71-27"></a>    <span class="dt">zmax =</span> <span class="dv">10</span>,</span>
<span id="cb71-28"><a href="analysis.html#cb71-28"></a>    <span class="dt">zmin =</span> <span class="dv">1</span>,</span>
<span id="cb71-29"><a href="analysis.html#cb71-29"></a>    <span class="dt">locations =</span> r2_state<span class="op">$</span>state, </span>
<span id="cb71-30"><a href="analysis.html#cb71-30"></a>    <span class="dt">locationmode =</span> <span class="st">&#39;USA-states&#39;</span></span>
<span id="cb71-31"><a href="analysis.html#cb71-31"></a>  ) <span class="op">%&gt;%</span></span>
<span id="cb71-32"><a href="analysis.html#cb71-32"></a><span class="st">  </span><span class="kw">colorbar</span>(<span class="dt">title =</span> <span class="st">&quot;# of Schools&quot;</span>) <span class="op">%&gt;%</span></span>
<span id="cb71-33"><a href="analysis.html#cb71-33"></a><span class="st">  </span><span class="kw">layout</span>(<span class="dt">geo =</span> g, <span class="dt">title =</span> <span class="st">&quot;Number of R2 Schools per State&quot;</span>)</span>
<span id="cb71-34"><a href="analysis.html#cb71-34"></a></span>
<span id="cb71-35"><a href="analysis.html#cb71-35"></a>r1_map</span></code></pre></div>
<div id="htmlwidget-79756cb159548da561f5" style="width:672px;height:480px;" class="plotly html-widget"></div>
<script type="application/json" data-for="htmlwidget-79756cb159548da561f5">{"x":{"visdat":{"12f46cd259ff":["function () ","plotlyVisDat"]},"cur_data":"12f46cd259ff","attrs":{"12f46cd259ff":{"alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"z":{},"span":[1],"colorscale":"Portland","zauto":false,"zmax":10,"zmin":1,"locations":["AL","AR","AZ","CA","CO","CT","DC","DE","FL","GA","HI","IA","IL","IN","KS","KY","LA","MA","MD","MI","MN","MO","MS","MT","NC","NE","NH","NJ","NM","NV","NY","OH","OK","OR","PA","RI","SC","TN","TX","UT","VA","WA","WI","WV"],"locationmode":"USA-states","inherit":true}},"layout":{"margin":{"b":40,"l":60,"t":25,"r":10},"mapType":"geo","scene":{"zaxis":{"title":"r1_state$n"}},"geo":{"domain":{"x":[0,1],"y":[0,1]},"scope":"usa","projection":{"type":"albers usa"},"lakecolor":"rgba(255,255,255,1)"},"hovermode":"closest","showlegend":false,"legend":{"yanchor":"top","y":0.5},"title":"Number of R1 Schools per State"},"source":"A","config":{"showSendToCloud":false},"data":[{"colorbar":{"title":"# of Schools","ticklen":2,"len":0.5,"lenmode":"fraction","y":1,"yanchor":"top"},"colorscale":"Portland","showscale":true,"z":[3,1,2,11,3,2,2,1,6,4,1,2,4,3,2,2,2,8,2,3,1,2,3,1,3,1,2,3,1,2,11,3,2,2,6,1,2,2,9,1,4,2,2,1],"zauto":false,"zmax":10,"zmin":1,"locations":["AL","AR","AZ","CA","CO","CT","DC","DE","FL","GA","HI","IA","IL","IN","KS","KY","LA","MA","MD","MI","MN","MO","MS","MT","NC","NE","NH","NJ","NM","NV","NY","OH","OK","OR","PA","RI","SC","TN","TX","UT","VA","WA","WI","WV"],"locationmode":"USA-states","type":"choropleth","marker":{"line":{"color":"rgba(31,119,180,1)","width":1}},"geo":"geo","frame":null}],"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.2,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb72-1"><a href="analysis.html#cb72-1"></a>r2_map</span></code></pre></div>
<div id="htmlwidget-34ce5504a4e1408783d4" style="width:672px;height:480px;" class="plotly html-widget"></div>
<script type="application/json" data-for="htmlwidget-34ce5504a4e1408783d4">{"x":{"visdat":{"12f4445612df":["function () ","plotlyVisDat"]},"cur_data":"12f4445612df","attrs":{"12f4445612df":{"alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"z":{},"span":[1],"colorscale":"Portland","zauto":false,"zmax":10,"zmin":1,"locations":["AK","AL","AR","AZ","CA","CO","DC","DE","FL","GA","ID","IL","IN","KS","LA","MA","MD","ME","MI","MO","MS","MT","NC","ND","NE","NJ","NM","NY","OH","OK","OR","PA","PR","RI","SD","TN","TX","UT","VA","VT","WI","WV","WY"],"locationmode":"USA-states","inherit":true}},"layout":{"margin":{"b":40,"l":60,"t":25,"r":10},"mapType":"geo","scene":{"zaxis":{"title":"r2_state$n"}},"geo":{"domain":{"x":[0,1],"y":[0,1]},"scope":"usa","projection":{"type":"albers usa"},"lakecolor":"rgba(255,255,255,1)"},"hovermode":"closest","showlegend":false,"legend":{"yanchor":"top","y":0.5},"title":"Number of R2 Schools per State"},"source":"A","config":{"showSendToCloud":false},"data":[{"colorbar":{"title":"# of Schools","ticklen":2,"len":0.5,"lenmode":"fraction","y":1,"yanchor":"top"},"colorscale":"Portland","showscale":true,"z":[1,2,2,3,6,3,4,1,4,4,3,6,2,1,3,5,3,2,5,4,1,1,6,2,1,6,1,7,9,1,1,4,2,1,2,4,9,2,3,1,1,1,1],"zauto":false,"zmax":10,"zmin":1,"locations":["AK","AL","AR","AZ","CA","CO","DC","DE","FL","GA","ID","IL","IN","KS","LA","MA","MD","ME","MI","MO","MS","MT","NC","ND","NE","NJ","NM","NY","OH","OK","OR","PA","PR","RI","SD","TN","TX","UT","VA","VT","WI","WV","WY"],"locationmode":"USA-states","type":"choropleth","marker":{"line":{"color":"rgba(31,119,180,1)","width":1}},"geo":"geo","frame":null}],"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.2,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
<p><strong>RACE</strong></p>
<p>The prelimary examination of the demographics data revealed that all of the race values, except for the proportion of white students, had a significant right skew. While the distributions are not normal, they are symmetric and bounded, which prevents extreme outliers. Below we provide a violin plot showing the distribution for each of the race variables grouped by their Carnegie classification. The mean is marked by a red bar, and the median is marked by a black bar.</p>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb73-1"><a href="analysis.html#cb73-1"></a>dem_pal &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;darkolivegreen&quot;</span>, <span class="st">&quot;darkolivegreen3&quot;</span>, <span class="st">&quot;dodgerblue4&quot;</span>, <span class="st">&quot;deepskyblue&quot;</span>, <span class="st">&quot;lavenderblush4&quot;</span>, <span class="st">&quot;lavenderblush2&quot;</span>, <span class="st">&quot;palevioletred1&quot;</span>, <span class="st">&quot;rosybrown1&quot;</span>,  <span class="st">&quot;tomato2&quot;</span>,  <span class="st">&quot;sienna 1&quot;</span>, <span class="st">&quot;slateblue3&quot;</span>, <span class="st">&quot;thistle1&quot;</span>, <span class="st">&quot;orange&quot;</span>, <span class="st">&quot;navajowhite2&quot;</span>, <span class="st">&quot;lightskyblue3&quot;</span>, <span class="st">&quot;lightsteelblue1&quot;</span>)</span>
<span id="cb73-2"><a href="analysis.html#cb73-2"></a>  </span>
<span id="cb73-3"><a href="analysis.html#cb73-3"></a>race_demographics &lt;-<span class="st"> </span>cdem <span class="op">%&gt;%</span></span>
<span id="cb73-4"><a href="analysis.html#cb73-4"></a><span class="st">  </span><span class="kw">select</span>(university, r_status, white, black, hispanic, asian, indigenous, nhpi, nra, unknown) <span class="op">%&gt;%</span></span>
<span id="cb73-5"><a href="analysis.html#cb73-5"></a><span class="st">  </span><span class="kw">gather</span>(<span class="st">&quot;race&quot;</span>, <span class="st">&quot;percentage&quot;</span>, <span class="dv">3</span><span class="op">:</span><span class="dv">10</span>, <span class="op">-</span>university)</span>
<span id="cb73-6"><a href="analysis.html#cb73-6"></a></span>
<span id="cb73-7"><a href="analysis.html#cb73-7"></a>race_demographics <span class="op">%&gt;%</span></span>
<span id="cb73-8"><a href="analysis.html#cb73-8"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> <span class="kw">factor</span>(r_status), <span class="dt">y =</span> percentage, <span class="dt">fill =</span> <span class="kw">interaction</span>(r_status, race))) <span class="op">+</span></span>
<span id="cb73-9"><a href="analysis.html#cb73-9"></a><span class="st">  </span><span class="kw">geom_violin</span>() <span class="op">+</span><span class="st"> </span></span>
<span id="cb73-10"><a href="analysis.html#cb73-10"></a><span class="st">  </span><span class="kw">stat_summary</span>(<span class="dt">fun=</span>mean, <span class="dt">geom=</span><span class="st">&quot;crossbar&quot;</span>, <span class="dt">linetype =</span> <span class="dv">1</span>, <span class="dt">size=</span>.<span class="dv">2</span>, <span class="dt">color =</span> <span class="st">&quot;red&quot;</span>) <span class="op">+</span><span class="st"> </span></span>
<span id="cb73-11"><a href="analysis.html#cb73-11"></a><span class="st">  </span><span class="kw">stat_summary</span>(<span class="dt">fun=</span>median, <span class="dt">geom=</span><span class="st">&quot;crossbar&quot;</span>, <span class="dt">linetype =</span> <span class="dv">1</span>, <span class="dt">size=</span>.<span class="dv">2</span>, <span class="dt">color =</span> <span class="st">&quot;black&quot;</span>) <span class="op">+</span></span>
<span id="cb73-12"><a href="analysis.html#cb73-12"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Racial Demographics by Carnegie Classification&quot;</span>, </span>
<span id="cb73-13"><a href="analysis.html#cb73-13"></a>       <span class="dt">subtitle =</span> <span class="st">&quot;Red line = mean | Black line = median</span><span class="ch">\n</span><span class="st">&quot;</span>,</span>
<span id="cb73-14"><a href="analysis.html#cb73-14"></a>       <span class="dt">x =</span> <span class="st">&quot; &quot;</span>, </span>
<span id="cb73-15"><a href="analysis.html#cb73-15"></a>       <span class="dt">y =</span> <span class="st">&quot;% of Student Body&quot;</span>) <span class="op">+</span><span class="st"> </span></span>
<span id="cb73-16"><a href="analysis.html#cb73-16"></a><span class="st">  </span><span class="kw">facet_wrap</span>(<span class="op">~</span><span class="kw">as.factor</span>(race), <span class="dt">nrow =</span> <span class="dv">5</span>) <span class="op">+</span><span class="st"> </span></span>
<span id="cb73-17"><a href="analysis.html#cb73-17"></a><span class="st">  </span><span class="kw">scale_fill_manual</span>(<span class="dt">values =</span> dem_pal) <span class="op">+</span><span class="st"> </span></span>
<span id="cb73-18"><a href="analysis.html#cb73-18"></a><span class="st">  </span><span class="kw">theme_gray</span>() <span class="op">+</span><span class="st"> </span></span>
<span id="cb73-19"><a href="analysis.html#cb73-19"></a><span class="st">  </span><span class="kw">theme</span>(<span class="dt">axis.title.y =</span> <span class="kw">element_text</span>(<span class="dt">margin =</span> <span class="kw">margin</span>(<span class="dt">t =</span> <span class="dv">0</span>, <span class="dt">r =</span> <span class="dv">20</span>, <span class="dt">b =</span> <span class="dv">0</span>, <span class="dt">l =</span> <span class="dv">0</span>)), </span>
<span id="cb73-20"><a href="analysis.html#cb73-20"></a>        <span class="dt">plot.title =</span> <span class="kw">element_text</span>(<span class="dt">hjust =</span> <span class="fl">.5</span>), </span>
<span id="cb73-21"><a href="analysis.html#cb73-21"></a>        <span class="dt">legend.position =</span> <span class="st">&quot;none&quot;</span>)</span></code></pre></div>
<p><img src="CollegeScorecardEDA_files/figure-html/unnamed-chunk-34-1.png" width="672" /></p>
<p>The five number summary for the ‘white variable’, along with the skewness and kurtosis, are reported below.</p>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb74-1"><a href="analysis.html#cb74-1"></a><span class="co"># DEMOGRAPHICS AT R1&#39;S - WHITE STUDENTS </span></span>
<span id="cb74-2"><a href="analysis.html#cb74-2"></a></span>
<span id="cb74-3"><a href="analysis.html#cb74-3"></a><span class="kw">summary</span>(demR1<span class="op">$</span>white)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##  0.0573  0.3900  0.5072  0.5129  0.6763  0.8408</code></pre>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb76-1"><a href="analysis.html#cb76-1"></a><span class="kw">skewness</span>(demR1<span class="op">$</span>white)</span></code></pre></div>
<pre><code>## [1] -0.2433317</code></pre>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb78-1"><a href="analysis.html#cb78-1"></a><span class="kw">kurtosis</span>(demR1<span class="op">$</span>white)</span></code></pre></div>
<pre><code>## [1] 2.272319</code></pre>
<div class="sourceCode" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb80-1"><a href="analysis.html#cb80-1"></a><span class="co"># DEMOGRAPHICS AT R2&#39;S - WHITE STUDENTS </span></span>
<span id="cb80-2"><a href="analysis.html#cb80-2"></a></span>
<span id="cb80-3"><a href="analysis.html#cb80-3"></a><span class="kw">summary</span>(demR2<span class="op">$</span>white)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##  0.0000  0.4507  0.6242  0.5529  0.7326  0.9348</code></pre>
<div class="sourceCode" id="cb82"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb82-1"><a href="analysis.html#cb82-1"></a><span class="kw">skewness</span>(demR2<span class="op">$</span>white)</span></code></pre></div>
<pre><code>## [1] -0.9043165</code></pre>
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb84-1"><a href="analysis.html#cb84-1"></a><span class="kw">kurtosis</span>(demR2<span class="op">$</span>white)</span></code></pre></div>
<pre><code>## [1] 2.917131</code></pre>
<p><strong>GENDER</strong></p>
<pre><code>##   female 
## -1.33759</code></pre>
<pre><code>##   female 
## 14.67132</code></pre>
<pre><code>##    female 
## -1.350992</code></pre>
<pre><code>##   female 
## 8.874628</code></pre>
<div class="sourceCode" id="cb90"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb90-1"><a href="analysis.html#cb90-1"></a><span class="co">#Universities with the highest female/male ratio, the top 10 are mostly R2&#39;s for both categories</span></span>
<span id="cb90-2"><a href="analysis.html#cb90-2"></a></span>
<span id="cb90-3"><a href="analysis.html#cb90-3"></a>cdem <span class="op">%&gt;%</span></span>
<span id="cb90-4"><a href="analysis.html#cb90-4"></a><span class="st">  </span><span class="kw">arrange</span>(<span class="kw">desc</span>(female)) <span class="op">%&gt;%</span></span>
<span id="cb90-5"><a href="analysis.html#cb90-5"></a><span class="st">  </span><span class="kw">filter</span>(female <span class="op">&gt;</span><span class="st"> </span><span class="fl">.50</span>) <span class="op">%&gt;%</span></span>
<span id="cb90-6"><a href="analysis.html#cb90-6"></a><span class="st">  </span><span class="kw">distinct</span>(university, <span class="dt">.keep_all =</span> <span class="ot">TRUE</span>) <span class="op">%&gt;%</span></span>
<span id="cb90-7"><a href="analysis.html#cb90-7"></a><span class="st">  </span><span class="kw">head</span>(<span class="dv">10</span>)</span></code></pre></div>
<pre><code>##    control                                 university r_status state    female
## 1        2                Thomas Jefferson University       R2    PA 0.7743842
## 2        1 CUNY Graduate School and University Center       R1    NY 0.7729469
## 3        2                   Clark Atlanta University       R2    GA 0.7631579
## 4        2                             The New School       R2    NY 0.7536302
## 5        2               Nova Southeastern University       R2    FL 0.7459016
## 6        2                  University of New England       R2    ME 0.7390681
## 7        2                   Azusa Pacific University       R2    CA 0.7258883
## 8        2                          Howard University       R2    DC 0.7177579
## 9        2                         Hampton University       R2    VA 0.6915352
## 10       2                  Loyola University Chicago       R2    IL 0.6876623
##    first_gen poverty_rate     veteran unemp_rate  white  black hispanic  asian
## 1  0.3293737     8.770079 0.004961565   3.535827 0.7195 0.0705   0.0136 0.0935
## 2  0.4395604    14.690000 0.015700483   4.900000 0.2200 0.2893   0.3135 0.1183
## 3  0.3158522     8.770079 0.004961565   3.535827 0.0004 0.8366   0.0040 0.0018
## 4  0.1944012     8.770079 0.004961565   3.535827 0.3297 0.0548   0.1195 0.0926
## 5  0.3733401     8.770079 0.007741348   3.535827 0.3296 0.1617   0.2988 0.0972
## 6  0.2207308     8.770079 0.004961565   3.535827 0.8274 0.0127   0.0013 0.0354
## 7  0.3798260     7.950000 0.005801305   3.830000 0.3726 0.0611   0.3322 0.0950
## 8  0.2363936    10.550000 0.004961565   4.430000 0.0222 0.8863   0.0092 0.0141
## 9  0.1975117     9.570000 0.004961565   4.010000 0.0142 0.9593   0.0131 0.0014
## 10 0.2651357     8.770079 0.004545454   3.535827 0.5814 0.0444   0.1425 0.1156
##    indigenous   nhpi    nra unknown   year
## 1      0.0000 0.0000 0.0081  0.0664   2015
## 2      0.0024 0.0048 0.0228  0.0000 latest
## 3      0.0011 0.0000 0.0241  0.1321   2015
## 4      0.0011 0.0016 0.3234  0.0400   2016
## 5      0.0026 0.0009 0.0572  0.0319   2016
## 6      0.0042 0.0000 0.0034  0.1021   2016
## 7      0.0029 0.0106 0.0310  0.0233 latest
## 8      0.0013 0.0052 0.0616  0.0000 latest
## 9      0.0025 0.0003 0.0082  0.0008 latest
## 10     0.0006 0.0028 0.0490  0.0139   2015</code></pre>
<div class="sourceCode" id="cb92"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb92-1"><a href="analysis.html#cb92-1"></a>cdem <span class="op">%&gt;%</span></span>
<span id="cb92-2"><a href="analysis.html#cb92-2"></a><span class="st">  </span><span class="kw">arrange</span>(female) <span class="op">%&gt;%</span></span>
<span id="cb92-3"><a href="analysis.html#cb92-3"></a><span class="st">  </span><span class="kw">filter</span>(female <span class="op">&lt;</span><span class="st"> </span><span class="fl">.50</span>) <span class="op">%&gt;%</span></span>
<span id="cb92-4"><a href="analysis.html#cb92-4"></a><span class="st">  </span><span class="kw">distinct</span>(university, <span class="dt">.keep_all =</span> <span class="ot">TRUE</span>) <span class="op">%&gt;%</span></span>
<span id="cb92-5"><a href="analysis.html#cb92-5"></a><span class="st">  </span><span class="kw">head</span>(<span class="dv">10</span>)</span></code></pre></div>
<pre><code>##    control                                    university r_status state
## 1        1            New Jersey Institute of Technology       R1    NJ
## 2        1 Missouri University of Science and Technology       R2    MO
## 3        1                      Colorado School of Mines       R2    CO
## 4        1             Michigan Technological University       R2    MI
## 5        2              Illinois Institute of Technology       R2    IL
## 6        2               Stevens Institute of Technology       R2    NJ
## 7        2                           Clarkson University       R2    NY
## 8        2              Rensselaer Polytechnic Institute       R1    NY
## 9        2             Rochester Institute of Technology       R2    NY
## 10       2               Worcester Polytechnic Institute       R2    MA
##       female first_gen poverty_rate     veteran unemp_rate  white  black
## 1  0.1898865 0.3375479     7.624656 0.003439973   3.292901 0.3348 0.0857
## 2  0.2278168 0.2257366     8.770079 0.004961565   3.535827 0.7815 0.0351
## 3  0.2631579 0.1719745     8.770079 0.004961565   3.535827 0.7471 0.0104
## 4  0.2765753 0.1732010     8.770079 0.004961565   3.535827 0.8609 0.0108
## 5  0.2832370 0.3137255     8.770079 0.004961565   3.535827 0.3257 0.0585
## 6  0.2847358 0.1549439     5.680000 0.004961565   3.140000 0.6433 0.0219
## 7  0.2998555 0.1528710     7.160000 0.004961565   3.590000 0.8113 0.0245
## 8  0.3294118 0.1306505     7.624656 0.003724733   3.292901 0.5907 0.0308
## 9  0.3355602 0.2022427     8.770079 0.004961565   3.535827 0.6580 0.0495
## 10 0.3477952 0.1429619     8.770079 0.004961565   3.535827 0.6294 0.0232
##    hispanic  asian indigenous   nhpi    nra unknown   year
## 1    0.2210 0.2214     0.0006 0.0006 0.0443  0.0604   2015
## 2    0.0311 0.0299     0.0037 0.0007 0.0566  0.0348   2015
## 3    0.0693 0.0488     0.0013 0.0007 0.0589  0.0088   2015
## 4    0.0185 0.0105     0.0037 0.0005 0.0421  0.0254   2015
## 5    0.1553 0.1300     0.0034 0.0014 0.2648  0.0428   2015
## 6    0.1137 0.1459     0.0009 0.0000 0.0351  0.0392 latest
## 7    0.0473 0.0369     0.0030 0.0000 0.0228  0.0188 latest
## 8    0.0813 0.1012     0.0014 0.0002 0.1062  0.0187   2015
## 9    0.0711 0.0756     0.0018 0.0002 0.0585  0.0542   2015
## 10   0.0843 0.0457     0.0024 0.0000 0.1226  0.0625   2015</code></pre>
<div class="sourceCode" id="cb94"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb94-1"><a href="analysis.html#cb94-1"></a>R1s &lt;-<span class="st"> </span>cdem <span class="op">%&gt;%</span></span>
<span id="cb94-2"><a href="analysis.html#cb94-2"></a><span class="st">  </span><span class="kw">filter</span>(r_status <span class="op">==</span><span class="st"> &quot;R1&quot;</span>)</span>
<span id="cb94-3"><a href="analysis.html#cb94-3"></a></span>
<span id="cb94-4"><a href="analysis.html#cb94-4"></a><span class="kw">ggplot</span>(cdem, <span class="kw">aes</span>(<span class="dt">x =</span> female)) <span class="op">+</span><span class="st"> </span></span>
<span id="cb94-5"><a href="analysis.html#cb94-5"></a><span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">bins =</span> <span class="dv">40</span>, <span class="dt">color =</span> <span class="st">&quot;black&quot;</span>, <span class="dt">fill =</span> <span class="st">&quot;pink&quot;</span>) <span class="op">+</span><span class="st"> </span></span>
<span id="cb94-6"><a href="analysis.html#cb94-6"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Distribution of Female/Male Gender ratio at R1s&quot;</span>)</span></code></pre></div>
<p><img src="CollegeScorecardEDA_files/figure-html/unnamed-chunk-38-1.png" width="672" /></p>
<div class="sourceCode" id="cb95"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb95-1"><a href="analysis.html#cb95-1"></a>R2s &lt;-<span class="st"> </span>cdem <span class="op">%&gt;%</span></span>
<span id="cb95-2"><a href="analysis.html#cb95-2"></a><span class="st">  </span><span class="kw">filter</span>(r_status <span class="op">==</span><span class="st"> &quot;R2&quot;</span>)</span>
<span id="cb95-3"><a href="analysis.html#cb95-3"></a></span>
<span id="cb95-4"><a href="analysis.html#cb95-4"></a><span class="kw">ggplot</span>(R2s, <span class="kw">aes</span>(<span class="dt">x =</span> female)) <span class="op">+</span><span class="st"> </span></span>
<span id="cb95-5"><a href="analysis.html#cb95-5"></a><span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">bins =</span> <span class="dv">40</span>, <span class="dt">color =</span> <span class="st">&quot;black&quot;</span>, <span class="dt">fill =</span> <span class="st">&quot;skyblue&quot;</span>) <span class="op">+</span><span class="st"> </span></span>
<span id="cb95-6"><a href="analysis.html#cb95-6"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Distribution of Female/Male Gender ratio at R2s&quot;</span>)</span></code></pre></div>
<p><img src="CollegeScorecardEDA_files/figure-html/unnamed-chunk-38-2.png" width="672" /></p>
<p><strong>OTHER DEMOGRAPHICS</strong></p>
<p>The non-racial variables (i.e., gender, first generation status, veteran status) did not posess the same skew. However, the mean was inflated due to how we coded NA’s resulting in peculiar looking violin plots.</p>
<div class="sourceCode" id="cb96"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb96-1"><a href="analysis.html#cb96-1"></a><span class="co">#Demographics for sparse columns </span></span>
<span id="cb96-2"><a href="analysis.html#cb96-2"></a></span>
<span id="cb96-3"><a href="analysis.html#cb96-3"></a>other_demographics &lt;-<span class="st"> </span>cdem <span class="op">%&gt;%</span></span>
<span id="cb96-4"><a href="analysis.html#cb96-4"></a><span class="st">  </span><span class="kw">select</span>(university, r_status, female, first_gen, veteran) <span class="op">%&gt;%</span></span>
<span id="cb96-5"><a href="analysis.html#cb96-5"></a><span class="st">  </span><span class="kw">gather</span>(<span class="st">&quot;demographic&quot;</span>, <span class="st">&quot;percentage&quot;</span>, <span class="dv">3</span><span class="op">:</span><span class="dv">5</span>, <span class="op">-</span>university)</span>
<span id="cb96-6"><a href="analysis.html#cb96-6"></a></span>
<span id="cb96-7"><a href="analysis.html#cb96-7"></a>other_plot &lt;-<span class="st"> </span>other_demographics <span class="op">%&gt;%</span></span>
<span id="cb96-8"><a href="analysis.html#cb96-8"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> <span class="kw">factor</span>(r_status), <span class="dt">y =</span> percentage, <span class="dt">fill =</span> <span class="kw">interaction</span>(r_status, demographic))) <span class="op">+</span></span>
<span id="cb96-9"><a href="analysis.html#cb96-9"></a><span class="st">  </span><span class="kw">geom_violin</span>() <span class="op">+</span><span class="st"> </span></span>
<span id="cb96-10"><a href="analysis.html#cb96-10"></a><span class="st">  </span><span class="kw">stat_summary</span>(<span class="dt">fun=</span>mean, <span class="dt">geom=</span><span class="st">&quot;crossbar&quot;</span>, <span class="dt">linetype =</span> <span class="dv">2</span>, <span class="dt">size=</span>.<span class="dv">1</span>, <span class="dt">color =</span> <span class="st">&quot;red&quot;</span>) <span class="op">+</span><span class="st"> </span></span>
<span id="cb96-11"><a href="analysis.html#cb96-11"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Other Demographic Factors by Carnegie Classification&quot;</span>, </span>
<span id="cb96-12"><a href="analysis.html#cb96-12"></a>       <span class="dt">subtitle =</span> <span class="st">&quot;&quot;</span>,</span>
<span id="cb96-13"><a href="analysis.html#cb96-13"></a>       <span class="dt">x =</span> <span class="st">&quot; &quot;</span>, </span>
<span id="cb96-14"><a href="analysis.html#cb96-14"></a>       <span class="dt">y =</span> <span class="st">&quot;% of Student Body&quot;</span>) <span class="op">+</span><span class="st"> </span></span>
<span id="cb96-15"><a href="analysis.html#cb96-15"></a><span class="st">  </span><span class="kw">facet_wrap</span>(<span class="op">~</span><span class="kw">as.factor</span>(demographic), <span class="dt">nrow =</span> <span class="dv">5</span>) <span class="op">+</span><span class="st"> </span></span>
<span id="cb96-16"><a href="analysis.html#cb96-16"></a><span class="st">  </span><span class="kw">scale_fill_brewer</span>(<span class="st">&quot;Paired&quot;</span>) <span class="op">+</span><span class="st"> </span></span>
<span id="cb96-17"><a href="analysis.html#cb96-17"></a><span class="st">  </span><span class="kw">theme_gray</span>() <span class="op">+</span><span class="st"> </span></span>
<span id="cb96-18"><a href="analysis.html#cb96-18"></a><span class="st">  </span><span class="kw">theme</span>(<span class="dt">axis.title.y =</span> <span class="kw">element_text</span>(<span class="dt">margin =</span> <span class="kw">margin</span>(<span class="dt">t =</span> <span class="dv">0</span>, <span class="dt">r =</span> <span class="dv">20</span>, <span class="dt">b =</span> <span class="dv">0</span>, <span class="dt">l =</span> <span class="dv">0</span>)), </span>
<span id="cb96-19"><a href="analysis.html#cb96-19"></a>        <span class="dt">plot.title =</span> <span class="kw">element_text</span>(<span class="dt">hjust =</span> <span class="fl">.5</span>), </span>
<span id="cb96-20"><a href="analysis.html#cb96-20"></a>        <span class="dt">legend.position =</span> <span class="st">&quot;none&quot;</span>)</span>
<span id="cb96-21"><a href="analysis.html#cb96-21"></a></span>
<span id="cb96-22"><a href="analysis.html#cb96-22"></a>other_plot</span></code></pre></div>
<p><img src="CollegeScorecardEDA_files/figure-html/unnamed-chunk-39-1.png" width="576" /></p>
</div>
</div>
<div id="financial-descriptive-statistics" class="section level2">
<h2><span class="header-section-number">5.3</span> Financial Descriptive Statistics</h2>
<div class="sourceCode" id="cb97"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb97-1"><a href="analysis.html#cb97-1"></a><span class="co"># Cost</span></span>
<span id="cb97-2"><a href="analysis.html#cb97-2"></a><span class="kw">print</span>(<span class="st">&#39;Tuition cost&#39;</span>)</span></code></pre></div>
<pre><code>## [1] &quot;Tuition cost&quot;</code></pre>
<div class="sourceCode" id="cb99"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb99-1"><a href="analysis.html#cb99-1"></a><span class="kw">summary</span>(finR1<span class="op">$</span>costt4_a)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA&#39;s 
##   16927   24464   28408   38695   66923   75735       1</code></pre>
<div class="sourceCode" id="cb101"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb101-1"><a href="analysis.html#cb101-1"></a>cost_hist1 &lt;-<span class="st"> </span><span class="kw">ggplot</span>(finR1, <span class="kw">aes</span>(<span class="dt">x =</span>costt4_a)) <span class="op">+</span><span class="st"> </span></span>
<span id="cb101-2"><a href="analysis.html#cb101-2"></a><span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">bins =</span> <span class="dv">40</span>, <span class="dt">color =</span> <span class="st">&quot;black&quot;</span>, <span class="dt">fill =</span> <span class="st">&quot;red&quot;</span>) <span class="op">+</span></span>
<span id="cb101-3"><a href="analysis.html#cb101-3"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Distribution of Tuition Costs at R1s&quot;</span>, </span>
<span id="cb101-4"><a href="analysis.html#cb101-4"></a>       <span class="dt">subtitle =</span> <span class="st">&quot;&quot;</span>, </span>
<span id="cb101-5"><a href="analysis.html#cb101-5"></a>       <span class="dt">x =</span> <span class="st">&quot;Cost (in American dollars)&quot;</span>, </span>
<span id="cb101-6"><a href="analysis.html#cb101-6"></a>       <span class="dt">y =</span> <span class="st">&quot;Frequency&quot;</span>) </span>
<span id="cb101-7"><a href="analysis.html#cb101-7"></a>cost_hist1</span></code></pre></div>
<p><img src="CollegeScorecardEDA_files/figure-html/unnamed-chunk-40-1.png" width="672" /></p>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA&#39;s 
##   11299   21266   24098   33613   51214   71875       4</code></pre>
<p><img src="CollegeScorecardEDA_files/figure-html/unnamed-chunk-41-1.png" width="672" /></p>
<div class="sourceCode" id="cb103"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb103-1"><a href="analysis.html#cb103-1"></a><span class="co"># Students debt</span></span>
<span id="cb103-2"><a href="analysis.html#cb103-2"></a><span class="kw">print</span>(<span class="st">&#39;Student debt&#39;</span>)</span></code></pre></div>
<pre><code>## [1] &quot;Student debt&quot;</code></pre>
<div class="sourceCode" id="cb105"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb105-1"><a href="analysis.html#cb105-1"></a><span class="kw">summary</span>(finR1<span class="op">$</span>grad_debt_mdn)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    8700   17634   20000   19652   22027   27000</code></pre>
<div class="sourceCode" id="cb107"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb107-1"><a href="analysis.html#cb107-1"></a>debt_hist1 &lt;-<span class="st"> </span><span class="kw">ggplot</span>(finR1, <span class="kw">aes</span>(<span class="dt">x =</span> grad_debt_mdn)) <span class="op">+</span><span class="st"> </span></span>
<span id="cb107-2"><a href="analysis.html#cb107-2"></a><span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">bins =</span> <span class="dv">40</span>, <span class="dt">color =</span> <span class="st">&quot;black&quot;</span>, <span class="dt">fill =</span> <span class="st">&quot;cadetblue4&quot;</span>) <span class="op">+</span></span>
<span id="cb107-3"><a href="analysis.html#cb107-3"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Distribution of Median Student Debt at R1s&quot;</span>, </span>
<span id="cb107-4"><a href="analysis.html#cb107-4"></a>       <span class="dt">subtitle =</span> <span class="st">&quot;&quot;</span>, </span>
<span id="cb107-5"><a href="analysis.html#cb107-5"></a>       <span class="dt">x =</span> <span class="st">&quot;Median Debt (in American dollars)&quot;</span>, </span>
<span id="cb107-6"><a href="analysis.html#cb107-6"></a>       <span class="dt">y =</span> <span class="st">&quot;Frequency&quot;</span>) </span>
<span id="cb107-7"><a href="analysis.html#cb107-7"></a>debt_hist1</span></code></pre></div>
<p><img src="CollegeScorecardEDA_files/figure-html/unnamed-chunk-42-1.png" width="672" /></p>
<div class="sourceCode" id="cb108"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb108-1"><a href="analysis.html#cb108-1"></a><span class="kw">summary</span>(finR2<span class="op">$</span>grad_debt_mdn)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA&#39;s 
##    5500   20930   23167   22719   25000   30500       5</code></pre>
<div class="sourceCode" id="cb110"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb110-1"><a href="analysis.html#cb110-1"></a>debt_hist1 &lt;-<span class="st"> </span><span class="kw">ggplot</span>(finR2, <span class="kw">aes</span>(<span class="dt">x =</span> grad_debt_mdn)) <span class="op">+</span><span class="st"> </span></span>
<span id="cb110-2"><a href="analysis.html#cb110-2"></a><span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">bins =</span> <span class="dv">40</span>, <span class="dt">color =</span> <span class="st">&quot;black&quot;</span>, <span class="dt">fill =</span> <span class="st">&quot;cadetblue3&quot;</span>) <span class="op">+</span></span>
<span id="cb110-3"><a href="analysis.html#cb110-3"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Distribution of Median Student Debt at R2s&quot;</span>, </span>
<span id="cb110-4"><a href="analysis.html#cb110-4"></a>       <span class="dt">subtitle =</span> <span class="st">&quot;&quot;</span>, </span>
<span id="cb110-5"><a href="analysis.html#cb110-5"></a>       <span class="dt">x =</span> <span class="st">&quot;Median Debt (in American dollars)&quot;</span>, </span>
<span id="cb110-6"><a href="analysis.html#cb110-6"></a>       <span class="dt">y =</span> <span class="st">&quot;Frequency&quot;</span>) </span>
<span id="cb110-7"><a href="analysis.html#cb110-7"></a>debt_hist1</span></code></pre></div>
<p><img src="CollegeScorecardEDA_files/figure-html/unnamed-chunk-43-1.png" width="672" /></p>
<p><strong>Unemployment</strong></p>
<div class="sourceCode" id="cb111"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb111-1"><a href="analysis.html#cb111-1"></a><span class="kw">print</span>(<span class="st">&#39;Unemployment Rate&#39;</span>)</span></code></pre></div>
<pre><code>## [1] &quot;Unemployment Rate&quot;</code></pre>
<div class="sourceCode" id="cb113"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb113-1"><a href="analysis.html#cb113-1"></a><span class="kw">summary</span>(finR1<span class="op">$</span>unemp_rate)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   2.190   2.965   3.200   3.293   3.605   5.020</code></pre>
<div class="sourceCode" id="cb115"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb115-1"><a href="analysis.html#cb115-1"></a>unemp_hist1 &lt;-<span class="st"> </span><span class="kw">ggplot</span>(finR1, <span class="kw">aes</span>(<span class="dt">x =</span> unemp_rate)) <span class="op">+</span><span class="st"> </span></span>
<span id="cb115-2"><a href="analysis.html#cb115-2"></a><span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">bins =</span> <span class="dv">40</span>, <span class="dt">color =</span> <span class="st">&quot;black&quot;</span>, <span class="dt">fill =</span> <span class="st">&quot;darkseagreen4&quot;</span>) <span class="op">+</span></span>
<span id="cb115-3"><a href="analysis.html#cb115-3"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Distribution of Post-Graduation Unemployment rates at R1s&quot;</span>, </span>
<span id="cb115-4"><a href="analysis.html#cb115-4"></a>       <span class="dt">subtitle =</span> <span class="st">&quot;&quot;</span>, </span>
<span id="cb115-5"><a href="analysis.html#cb115-5"></a>       <span class="dt">x =</span> <span class="st">&quot;Unemployment Rate&quot;</span>, </span>
<span id="cb115-6"><a href="analysis.html#cb115-6"></a>       <span class="dt">y =</span> <span class="st">&quot;Frequency&quot;</span>) </span>
<span id="cb115-7"><a href="analysis.html#cb115-7"></a>unemp_hist1</span></code></pre></div>
<p><img src="CollegeScorecardEDA_files/figure-html/unnamed-chunk-44-1.png" width="672" /></p>
<div class="sourceCode" id="cb116"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb116-1"><a href="analysis.html#cb116-1"></a><span class="kw">summary</span>(finR2<span class="op">$</span>unemp_rate)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA&#39;s 
##   2.320   3.040   3.360   3.545   3.900   7.920       6</code></pre>
<div class="sourceCode" id="cb118"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb118-1"><a href="analysis.html#cb118-1"></a>unemp_hist2 &lt;-<span class="st"> </span><span class="kw">ggplot</span>(finR2, <span class="kw">aes</span>(<span class="dt">x =</span> unemp_rate)) <span class="op">+</span><span class="st"> </span></span>
<span id="cb118-2"><a href="analysis.html#cb118-2"></a><span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">bins =</span> <span class="dv">40</span>, <span class="dt">color =</span> <span class="st">&quot;black&quot;</span>, <span class="dt">fill =</span> <span class="st">&quot;darkseagreen3&quot;</span>) <span class="op">+</span></span>
<span id="cb118-3"><a href="analysis.html#cb118-3"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Distribution of Post-Graduation Unemployment rates at R2s&quot;</span>, </span>
<span id="cb118-4"><a href="analysis.html#cb118-4"></a>       <span class="dt">subtitle =</span> <span class="st">&quot;&quot;</span>, </span>
<span id="cb118-5"><a href="analysis.html#cb118-5"></a>       <span class="dt">x =</span> <span class="st">&quot;Unemployment Rate&quot;</span>, </span>
<span id="cb118-6"><a href="analysis.html#cb118-6"></a>       <span class="dt">y =</span> <span class="st">&quot;Frequency&quot;</span>) </span>
<span id="cb118-7"><a href="analysis.html#cb118-7"></a>unemp_hist2</span></code></pre></div>
<p><img src="CollegeScorecardEDA_files/figure-html/unnamed-chunk-45-1.png" width="672" /></p>
<div id="r1s-vs.-r2s" class="section level3">
<h3><span class="header-section-number">5.3.1</span> R1s vs. R2s</h3>
<p>Preliminary normality analysis of the median graduate debt distribution revealed levels of skewness that forbade the use of parametric comparison tests. A Wilcoxon signed-rank test was conducted in order to investigate the differences in median graduate debt between R1 and R2 institutions. Results indicate that median graduate debt significantly differed between R1 and R2 institutions (W = 982, p &lt; 0.01). While a difference in student debt was expected due to the aforementioned price of R1 institution tuition, descriptive statistics revealed graduates of R1 institutions graduated with less average debt (M = 19,652, SD = 3,750) than students from R2 institutions (M = 22,719, SD = 3,785).</p>
<div class="sourceCode" id="cb119"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb119-1"><a href="analysis.html#cb119-1"></a><span class="kw">wilcox.test</span>(<span class="dt">formula=</span>finR<span class="op">$</span>grad_debt_mdn<span class="op">~</span>finR<span class="op">$</span>r_status)</span></code></pre></div>
<pre><code>## 
##  Wilcoxon rank sum test with continuity correction
## 
## data:  finR$grad_debt_mdn by finR$r_status
## W = 4430.5, p-value = 2.092e-11
## alternative hypothesis: true location shift is not equal to 0</code></pre>
<p>In order to further explore student outcomes, the investigators turned their attention to the graduate unemployment rate. The distribution for unemployment exhibited skewness and kurtosis values within acceptable bounds so a Welch’s two-sample t-test was conducted in order to find whether there were significant differences in unemployment rates between R1 and R2 graduates. The test revealed significant differences in rates of unemployment between R1 and R2 graduates t(118.36) = -2.6055, p = 0.01, 95%C.I. [-0.44, -0.06]. On average, the unemployment rate for R1 graduates (M = 3.293, SD = 0.51) was lower than that observed for R2 graduates (M = 3.545, SD = 0.83)</p>
<div class="sourceCode" id="cb121"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb121-1"><a href="analysis.html#cb121-1"></a><span class="kw">t.test</span>(finR<span class="op">$</span>unemp_rate<span class="op">~</span>finR<span class="op">$</span>r_status)</span></code></pre></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  finR$unemp_rate by finR$r_status
## t = -2.7918, df = 208.77, p-value = 0.005728
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -0.41446370 -0.07138832
## sample estimates:
## mean in group 1 mean in group 2 
##        3.292901        3.535827</code></pre>
</div>
<div id="regression-model" class="section level3">
<h3><span class="header-section-number">5.3.2</span> Regression model</h3>
<p>The racial diversity proportion of an institution was examined as a potential moderator of the relationship between institution type (R1 vs. R2) and unemployment rate. In the first step of the regression analysis institution type was entered into the model and accounted for 5% of the variance in unemployment rate, which was significant, R2= 0.52, F(1,122) = 6.82, p = 0.01. In the second step of the regression analysis the interaction effect between institution type and racial diversity proportion were entered into the model and explained an additional 4% of the variance in unemployment rate, which was significant, R2= 0.04, F(1,121) = 8.57, p &lt; 0.05. Racial diversity proportion was entered into the model last and accounted for 24% of the variance in unemployment rate, which was significant, R2= 0.24, F(1,122) = 38.8 , p &lt; 0.01. Thus, racial diversity proportion was a significant moderator of the relationship between institution type and unemployment rate.</p>
<dl>
<dt><strong>Model step 1</strong></dt>
<dd>TEXT
</dd>
</dl>
<div class="sourceCode" id="cb123"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb123-1"><a href="analysis.html#cb123-1"></a>predictor &lt;-<span class="st"> </span>finR<span class="op">$</span>r_status</span>
<span id="cb123-2"><a href="analysis.html#cb123-2"></a>outcome &lt;-<span class="st"> </span>finR<span class="op">$</span>unemp_rate</span>
<span id="cb123-3"><a href="analysis.html#cb123-3"></a></span>
<span id="cb123-4"><a href="analysis.html#cb123-4"></a>simplelm &lt;-<span class="st"> </span><span class="kw">lm</span>(<span class="dt">formula =</span> outcome <span class="op">~</span><span class="st"> </span>predictor)</span></code></pre></div>
<dl>
<dt><strong>Model step 2</strong></dt>
<dd>TEXT
</dd>
</dl>
<div class="sourceCode" id="cb124"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb124-1"><a href="analysis.html#cb124-1"></a>predictor &lt;-<span class="st"> </span>demR<span class="op">$</span>white</span>
<span id="cb124-2"><a href="analysis.html#cb124-2"></a>outcome &lt;-<span class="st"> </span>finR<span class="op">$</span>unemp_rate</span>
<span id="cb124-3"><a href="analysis.html#cb124-3"></a></span>
<span id="cb124-4"><a href="analysis.html#cb124-4"></a>moderatorlm &lt;-<span class="st"> </span><span class="kw">lm</span>(<span class="dt">formula =</span> outcome <span class="op">~</span><span class="st"> </span>predictor)</span></code></pre></div>
<dl>
<dt><strong>Model step 3</strong></dt>
<dd>TEXT
</dd>
</dl>
<div class="sourceCode" id="cb125"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb125-1"><a href="analysis.html#cb125-1"></a>predictor &lt;-<span class="st"> </span><span class="kw">as.integer</span>(finR<span class="op">$</span>r_status)</span>
<span id="cb125-2"><a href="analysis.html#cb125-2"></a>moderator &lt;-<span class="st"> </span>demR<span class="op">$</span>white</span>
<span id="cb125-3"><a href="analysis.html#cb125-3"></a>interaction &lt;-<span class="st"> </span>predictor <span class="op">*</span><span class="st"> </span>moderator</span>
<span id="cb125-4"><a href="analysis.html#cb125-4"></a>outcome &lt;-<span class="st"> </span>finR<span class="op">$</span>unemp_rate</span>
<span id="cb125-5"><a href="analysis.html#cb125-5"></a></span>
<span id="cb125-6"><a href="analysis.html#cb125-6"></a>interactionlm &lt;-<span class="st"> </span><span class="kw">lm</span>(<span class="dt">formula =</span> outcome <span class="op">~</span><span class="st"> </span>interaction)</span></code></pre></div>
<dl>
<dt><strong>Complete model</strong></dt>
<dd>TEXT
</dd>
</dl>
<div class="sourceCode" id="cb126"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb126-1"><a href="analysis.html#cb126-1"></a>predictor &lt;-<span class="st"> </span><span class="kw">as.integer</span>(finR<span class="op">$</span>r_status)</span>
<span id="cb126-2"><a href="analysis.html#cb126-2"></a>moderator &lt;-<span class="st"> </span>demR<span class="op">$</span>white</span>
<span id="cb126-3"><a href="analysis.html#cb126-3"></a>interaction &lt;-<span class="st"> </span>predictor <span class="op">*</span><span class="st"> </span>moderator</span>
<span id="cb126-4"><a href="analysis.html#cb126-4"></a>outcome &lt;-<span class="st"> </span>finR<span class="op">$</span>unemp_rate</span>
<span id="cb126-5"><a href="analysis.html#cb126-5"></a></span>
<span id="cb126-6"><a href="analysis.html#cb126-6"></a>wlm &lt;-<span class="st"> </span><span class="kw">lm</span>(<span class="dt">formula =</span> outcome <span class="op">~</span><span class="st"> </span>predictor <span class="op">+</span><span class="st"> </span>moderator <span class="op">+</span><span class="st"> </span>interaction)</span></code></pre></div>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="clean.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="discussion.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/rstudio/bookdown-demo/edit/master/05-Analysis.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["CollegeScorecardEDA.pdf"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
